### ISSUE TITLE
UseTriggers in startUp

### ISSUE THREAD

**Issue by hassanrazakhalid** [koenbeuk/EntityFrameworkCore.Triggered#108]
Hi
i have million rows in Cities, States, Countries. However when i user trigger in start this slows how my initial seeding setup. I have waited like 10 minutes and then i have to comment below lines and then uncomment after initial seeding. I'm not sure whats happening under the hood that makes seeding so slow. I am not even triggering any event during Cities, States and Countries seeding.

```
// .UseTriggers(triggerOptions =>
            // {
            //     triggerOptions.AddTrigger<DeleteCustomerDocumentTrigger>();
            //     triggerOptions.AddTrigger<DeletePhysicialFileTrigger>();
            //     triggerOptions.AddTrigger<DeleteProviderDocumentTrigger>();
            // })
```

**Comment by koenbeuk** [comment]
Hi Hassan, I presume that you don't actually seed all millions of rows in during application startup? If so, you may be better off using something like BulkInsert from https://github.com/borisdj/EFCore.BulkExtensions

Adding 10 minutes however is not to be expected. Having triggers causes a slight overhead to your DbContext but unless you're actually invoking triggers, this should overhead should hardly be noticeable.

Some suggestions as to what you may try:
- Make sure that you're not accidentally invoking Triggers. You can still make a call to UseTriggers without having any trigger registered. It should then cause no noticeable performance overhead. Alternatively you may observe the Info level logs produced under scope EntityFrameworkCore.Triggered to see what is happening internally.
- Make sure that you don't have Info level logging enabled for Triggers when inserting large volumes of data.
- Implement Trigger interface explicitly (e.g. IBeforeSaveTrigger<Foo>) instead of using the Trigger base class from the Extension package. The latter will cause some additional performance overhead.

Let me know if the above helps.
