### ISSUE TITLE
Multiple triggers issue with disposed DBContext

### ISSUE THREAD

**Issue by ninomllr** [koenbeuk/EntityFrameworkCore.Triggered#128]
I run into an issue that the DBContext is disposed after the first trigger is done and when this trigger changes another entity with a trigger in it as well, then the second trigger fails, because the db context is already disposed. 

I set the DBContext to transient, but still the same issue. Is there some more info on states of this NuGet and how to solve this?

**Comment by bahtiyarozdere** [comment]
Having the same issue. As soon as I added second trigger and calling for a DbContext from dependency injection it throws this error on second call.
What I noticed is when I put a breakpoint in trigger constructor it is only called once. So DBContext is created once, and in second call it is disposed because the previous request is ended.

I am using dotnet core 3.1.

**Comment by koenbeuk** [comment]
@bahtiyarozdere 

Assuming that you're using version 1.4 of this project, can you help me reproduce this issue? I've setup a working project over here: https://github.com/koenbeuk/EFCoreTriggeredIssue128

Thanks

**Comment by ninomllr** [comment]
@koenbeuk this fixed my problem! wow, what a stupid mistake on my end :-) Thanks

**Comment by bahtiyarozdere** [comment]
> nd calling for a DbContext from dependency injection it throws this error on second call.

Sorry I saw this late. I will update the repo today if you still want to check it.

**Comment by koenbeuk** [comment]
@bahtiyarozdere That would be great, thanks!

**Comment by benmccallum** [comment]
We're getting a potentially similar/same issue. It feels like a "Scoped" service isn't scoped to an IServiceProvider scope, but to a DbContext's lifetime. So if you're using pooled db contexts, you can get problems if one dbcontext is used multiple times. I'll try make a repro

**Comment by benmccallum** [comment]
Yea so it seems to happen when I use `.AddAssemblyTriggers` rather than `.AddTrigger<T>`. 

I've repro'd it [here](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/pull/138), see the PR description. 

Essentially one of triggers relies on a factory, which in turn relies on IServiceProvider, but the second execution of this, the IServiceProvider is already disposed and can't resolve anything.

See the startup.cs for what works vs doesn't.

**Comment by benmccallum** [comment]
cc: @anthony-keller , looks like when this gets published we could swap back from `AddAssemblyTriggers(ServiceLifetime.Transient)` to `AddAssemblyTriggers()` (scoped) and it'd be ok. 

@koenbeuk , I do think aligning the two different registration APIs to use the same default lifetime would be better. It took me a moment to repro this as initially I tried without pooling; eventually I realised that was the difference and then could repro and was surprised to see Scoped all of a sudden. Thanks again!
