### ISSUE TITLE
DbContextFactory created with Scoped lifetime instead of Singleton

### ISSUE THREAD

**Issue by cdimitroulas** [koenbeuk/EntityFrameworkCore.Triggered#135]
I have seen previous issues about DbContextFactory and the suggestion was to use `AddTriggeredDbContextFactory` to solve those problems.

However, when we tried to do this it caused a bunch of other issues throughout the codebase because AddTriggeredDbContextFactory seems to cause the context factory to be changed to a scoped lifetime somehow.

We found that using `services.AddDbContextFactory<TDbContext>(builder => { ...}, ServiceLifetime.Transient);` solved the issues for us.

I am interested to know if you see any potential issues with using the context factory with a transient service lifetime like this? Our automated tests and passing and some manual tests show that the triggers are working correctly as expected but I worry that there might be some unexpected consequences that will bite us later down the line.

**Comment by cdimitroulas** [comment]
> AddTriggeredDbContextFactory should mirror the same API and feature set as is available with the default AddDbContextFactory. There is an overload that takes a ServiceLifetime such that you can configure it to be Transient however juding from code, this is not correctly [used](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/blob/master/src/EntityFrameworkCore.Triggered/Extensions/ServiceCollectionExtensions.cs#L82).
>
> This is certainly a bug, I will look into. I'm certainly also open for a PR

Indeed, it seems that this `Replace` call is causing the factory to be in a scoped lifetime instead of singleton. Should that line read `lifetime: lifetime` instead of `lifetime: ServiceLifetime.Scoped`?

**Comment by koenbeuk** [comment]
I suppose it does, I can't recall why I forced it to be a Scoped lifetime.

**Comment by cdimitroulas** [comment]
I opened a very basic PR, I didn't spend much time on it so please let me know if there are more changes required

**Comment by aescg1220** [comment]
@cdimitroulas same issue here (havent tried the AddTriggeredDbContextFactory yet), but in addition:
* When using a dbcontextfactory, none of the beforesave triggers function properly.  I suspect that these are actually separate dbcontexts due to having different ContextIds.

Can you attempt a beforesave trigger in your environment to see if it functions? (and if so, do the contexts share the same ContextId?)

**Comment by cdimitroulas** [comment]
In our setup the triggers are working as intended, but the fact that the lifetime was being changed from Singleton to Scoped caused runtime errors in other parts of our application where the DI system started throwing errors.

**Comment by aescg1220** [comment]
When I manually recreate the AddTriggeredDbContextFactory extension methods passing in the lifetime for the serviceCollection.Replace call, the before save triggers now have the same contextid!  great work, can't wait to pull it down.

**Comment by koenbeuk** [comment]
@cdimitroulas @aescg1220 I'm stuck with some other work at the moment but will investigate more in the coming days.

In short: In now recall why the Lifetime of the Registered DbContextFactory was set to Scoped was as it needs to access the current ServiceProvider (could also be Transient). AddTriggeredDbContextFactory does the following:

1. Call `AddDbContextFactory` which ensures that EF registers itself with the ServerCollection. With this, EF Registers a Service of type: `IDbContextFactory<MyDbContext>` with a lifetime as specified by the user.
2. Register the implementation type of `IDbContextFactory<MyDbContext>` as itself with the same lifetime (so that we can later still resolve it from DI)
3. Replace the Registration of the `IDbContextFactory<MyDbContext>` with a Scoped registration referring to `TriggeredDbContextFactory<MyDbContext>`.

As TriggeredDbContextFactory is registered as Scoped, it will create a new instance within each ServiceScope, hence each instance has captured the ServiceProvider associated with that Scope. Within its constructor it takes an Instance of the Original `IDbContextFactory<MyDbContext>` (which may still be registered as a singleton).

**Comment by koenbeuk** [comment]
> When I manually recreate the AddTriggeredDbContextFactory extension methods passing in the lifetime for the serviceCollection.Replace call, the before save triggers now have the same contextid! great work, can't wait to pull it down.

Have you tried using the current (out-of-the-box) `AddTriggeredDbContextFactory` extension method? Can you share a code sample demonstrating what's broken?

**Comment by aescg1220** [comment]
@koenbeuk 
sure, i'm using blazor with .net 6.
my dbcontext (UpdatesDbContext) inherits the standard DbContext from efcore.
my triggers are internal to a separate assembly which also houses the db context, so I have a method (UpdatesDbContext.Configure) for registering the trigger (beforesave).
i also have an initializer which simply migrates the database that runs when the app is built from the webapplicationbuilder.
i have two singleton services which both accept an idbcontextfactory in their constructor via DI (one of them is a hosted service)

#### Attempt 1
```csharp
builder.Services.AddDbContextFactory<UpdatesDbContext>(opts => UpdatesDbContext.Configure(opts.UseSqlite(connectionString)));
```

When it attempts to run the app, it throws this error:
System.InvalidOperationException: 'Cannot resolve scoped service 'Shared.UpdatesDbContext' from root provider.'

#### Attempt 2
```csharp
builder.Services.AddDbContextFactory<UpdatesDbContext>(
    opts => UpdatesDbContext.Configure(opts.UseSqlite(connectionString)),
    ServiceLifetime.Transient
);
```

Using this, the beforesavetrigger does fire and _seems_ to work properly, but the modifications made during the trigger are not saved. In this case, the dbcontext is different than the dbcontext which originally made the modification.

#### Attempt 3
```csharp
builder.Services.AddTriggeredDbContextFactory<UpdatesDbContext>(
    opts => UpdatesDbContext.Configure(opts.UseSqlite(connectionString))
);
```

When using this, the webapplicationbuilder.build() method throws the following exception
System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: NableMonitor.Data.UpdatesService Lifetime: Singleton ImplementationType: NableMonitor.Data.UpdatesService': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Shared.UpdatesDbContext]' from singleton 'NableMonitor.Data.UpdatesService'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: NableMonitor.Services.SynchronizerService': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Shared.UpdatesDbContext]' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.)'

#### Working Code
```csharp
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using NableMonitor.Data;
using NableMonitor.Hubs;
using NableMonitor.Services;
using Shared;

var builder = WebApplication.CreateBuilder(args);

//connectionstringbuilder needed for directory creation
var connectionStringBuilder = new SqliteConnectionStringBuilder(builder.Configuration.GetConnectionString("Default"));
var connectionString = connectionStringBuilder.ConnectionString;

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();
builder.Services.Configure<SynchronizationOptions>(builder.Configuration.GetRequiredSection(SynchronizationOptions.Synchronization));
builder.Services.AddSingleton<UpdatesService>();

////fails on app.Run with System.InvalidOperationException: 'Cannot resolve scoped service 'Shared.UpdatesDbContext' from root provider.'
//builder.Services.AddDbContextFactory<UpdatesDbContext>(opts => UpdatesDbContext.Configure(opts.UseSqlite(connectionString)));

////no changes made during the beforesave trigger are persisted
//builder.Services.AddDbContextFactory<UpdatesDbContext>(
//    opts => UpdatesDbContext.Configure(opts.UseSqlite(connectionString)),
//    ServiceLifetime.Transient
//);

////throws during builder.Build()
////System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: NableMonitor.Data.UpdatesService Lifetime: Singleton ImplementationType: NableMonitor.Data.UpdatesService': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Shared.UpdatesDbContext]' from singleton 'NableMonitor.Data.UpdatesService'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: NableMonitor.Services.SynchronizerService': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.IDbContextFactory`1[Shared.UpdatesDbContext]' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.)'
//builder.Services.AddTriggeredDbContextFactory<UpdatesDbContext>(
//    opts => UpdatesDbContext.Configure(opts.UseSqlite(connectionString))
//);

//fixes https://github.com/koenbeuk/EntityFrameworkCore.Triggered/issues/135.
builder.Services.AddTriggeredDbContextFactory2<UpdatesDbContext>(
    opts => UpdatesDbContext.Configure(opts.UseSqlite(connectionString))
);
builder.Services.AddHostedService<SynchronizerService>();
builder.Services.AddResponseCompression(opts => opts.MimeTypes = ResponseCompressionDefaults.MimeTypes.Append("application/octet-stream"));

var app = builder.Build();

//create the db directory and migrate the db
{
    Directory.CreateDirectory(Path.GetDirectoryName(connectionStringBuilder.DataSource)!);

    using var scope = app.Services.CreateScope();
    using var context = scope.ServiceProvider.GetRequiredService<IDbContextFactory<UpdatesDbContext>>().CreateDbContext();
    DbInitializer.Initialize(context);
}

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.MapBlazorHub();
app.MapHub<UpdatesHub>(UpdatesHub.Pattern);
app.MapFallbackToPage("/_Host");

app.Run();
```

**Comment by cdimitroulas** [comment]
> i have two singleton services which both accept an idbcontextfactory in their constructor via DI (one of them is a hosted service)

We had the same problem within our DB migrator and hosted services which are singletons. The error was the same as what @aescg1220 reported: `System.InvalidOperationException: 'Cannot resolve scoped service '*DbContext' from root provider.'`.

**Comment by aescg1220** [comment]
In theory could the call to replace be modified like this?

#### From:
```csharp
serviceCollection.Replace(ServiceDescriptor.Describe(
	serviceType: typeof(IDbContextFactory<TContext>),
	implementationFactory: serviceProvider => ActivatorUtilities.CreateInstance(serviceProvider, triggeredFactoryType, serviceProvider.GetRequiredService(serviceDescriptor.ImplementationType), serviceProvider),
	lifetime: ServiceLifetime.Scoped
));
```

#### To:
```csharp
serviceCollection.Replace(ServiceDescriptor.Describe(
	serviceType: typeof(IDbContextFactory<TContext>),
	implementationFactory: serviceProvider => ActivatorUtilities.CreateInstance(serviceProvider, triggeredFactoryType, serviceProvider.GetRequiredService(serviceDescriptor.ImplementationType), serviceProvider),
	lifetime: lifetime == ServiceLifetime.Singleton ? ServiceLifetime.Singleton : ServiceLifetime.Scoped
));
```

**Comment by aescg1220** [comment]
Did a bit of follow up research, and for my hosted service I was using [constructor injection](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#scope-scenarios) incorrectly.
In order to get the other singleton service working correctly, I had to adopt the same pattern (using the servicefactory).
With those two modifications, I was able to get the OOTB AddTriggeredDbContextFactory to work correctly.

This probably needs a wiki mention under DI.

**Comment by koenbeuk** [comment]
Thanks @aescg1220 @cdimitroulas for your input on this! I will take a closer look over the weekend

**Comment by koenbeuk** [comment]
> This library internally uses a scoped IDbContextFactory implementation

This is the current effect of calling `AddTriggeredDbContextPool`, `AddTriggeredDbContextFactory` and `AddTriggeredPooledDbContextFactory` and this should be fixed. 

This library needs to grab the current `ServiceProvider` that is used to either get an instance of `IDbContextFactory` or otherwise a Lease on an instance of a  DbContext in the pool (each instance essentially acts as a singleton in the latter case). By storing this `ServiceProvider`, this library can then associate that ServiceProvider instance with the DbContext so that triggers can resolve  services using the same ServiceProvider.

There is no need for this custom IDbContextFactory implementation to be registered as Scoped. Instead, Transient will work in both worlds. We should update these registrations to use a Transient registration instead.

> I'm still unclear on how this could be resolved without requiring developers to change to the IServiceScopeFactory pattern.

Once we update the registrations to `Transient`, we will be able to resolve a `IDbContextFactory` from the root ServiceProvider, as this is able to resolve Singleton and Transient services. Any trigger however that relies on a Scoped service will still cause issues as that root ServiceProvider is unable to deal with them. It therefore is strongly recommended to IServiceScope pattern as you highlighted above in singleton services.
