### ISSUE TITLE
Can only set applicationScopedServiceProvider once

### ISSUE THREAD

**Issue by anthony-keller** [koenbeuk/EntityFrameworkCore.Triggered#151]
**Version**
3.1.0

Since 3.1.0, our web applications that use Autofac have been experiencing this error:
`Can only set applicationScopedServiceProvider once`

I can try and create a repro solution if needed, but just wanted to check first to see whether there is anything obvious I can do to resolve the issue? When debugging into the symbols, both the `_applicationScopedServiceProvider` and the `serviceProvider` passed in are instances of `AutofacServiceProvider` but they must be different because it's passing the `!=` check.

Version 3.0.0 does not have this issue. Our micro-services projects (that don't use Autofac) don't have this issue.

**Comment by koenbeuk** [comment]
I'm assuming that you're not calling `ApplicationTriggerServiceProviderAccessor.SetTriggerServiceProvider` manually from your code (which is an internal API).

`SetTriggerServiceProvider` gets called when the DbContext gets resolved from [DI](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/blob/78a89625f8760c34efa09326e24893e2e6e527f9/src/EntityFrameworkCore.Triggered/Extensions/ServiceCollectionExtensions.cs#L50) (when using db context pooling or a db context factory). Judging from this, the same DbContext is getting reused by different ServiceProviders which often spells a bug somewhere.

I'm happy to take a closer look but a repro solution would be very much desired. Thanks!

**Comment by benmccallum** [comment]
This appears to be due to our use of Autofac. I've created a repro [here](https://github.com/benmccallum/EntityFrameworkCore.Triggered/tree/disposed-sp-repo).

**3.0.0 issue with MediatR**
On 3.0.0, we have an intermittent issue with the service provider being disposed before MediatR can spawn a notification handler. 
> System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it (or one of its parent scopes) has already been disposed.

Repro:
1. Checkout commit [20da48c308aaf18bb9490ba7e68685e8e19c80ec](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/commit/20da48c308aaf18bb9490ba7e68685e8e19c80ec)
2. Do a POST to `https://localhost:5001/api/course/add` - works
3. Do a second POST to the same url - fails.

**3.1.0 issue**
Bump to 3.1.0 and above issue is fixed, but only when Autofac isn't involved.

Introduce Autofac and 3.1.0, and we get the issue Anth report here. 
> System.InvalidOperationException: Can only set applicationScopedServiceProvider once

To repro:
1. Checkout commit [a2bf5962ca62bd534ef05c3737ef0f0fe9c0b09e](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/commit/a2bf5962ca62bd534ef05c3737ef0f0fe9c0b09e)
2. Do a POST to `https://localhost:5001/api/course/add` - instant failure

**Path forward**
Options:
1. Fix in EFC.Triggered or Autofac, wherever the problem lies?
2. We remove Autofac and move onto MS DI (a pretty big change for us, but do-able).

Keen to hear your thoughts @koenbeuk now that you could reproduce it and have a look.

**Comment by koenbeuk** [comment]
@benmccallum Thanks for the repro's!

Without diving into autofac but simply by observing: 

```csharp
using Autofac;
using Autofac.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;

var services = new ServiceCollection()
    .AddTransient(sp => { Console.WriteLine($"Foo activation by {sp.GetHashCode()}"); return new FooService(); });

{
    Console.WriteLine("When using MS DI:");
    using var msServiceProvider = services.BuildServiceProvider();
    msServiceProvider.GetService<FooService>();
    msServiceProvider.GetService<FooService>();
}

{
    Console.WriteLine("When using Autofac:");
    var builder = new ContainerBuilder();
    builder.Populate(services);
    using var autofacServiceProvider = builder.Build();
    autofacServiceProvider.Resolve<FooService>();
    autofacServiceProvider.Resolve<FooService>();
}
```

will output:

```
When using MS DI:
Foo activation by 23458411
Foo activation by 23458411
When using Autofac:
Foo activation by 47096010
Foo activation by 21210914
```

Which implies that autofac creates a new intermediate ServiceProvider- even though these different service providers seem to share the same scoped and singleton instances.

The error check in this library is therefore inaccurate:

```csharp
if (_applicationScopedServiceProvider is not null && _applicationScopedServiceProvider != serviceProvider)
    throw new InvalidOperationException("Can only set applicationScopedServiceProvider once");
```

When using Microsoft.Extensions.DependencyInjection, the above check can catch leaky DBContexts which gets reused by different ServiceProviders (often due to pooling).

I suppose we can simply get rid of that check altogether- or have an option exposed that can disable that check.

**Comment by anthony-keller** [comment]
Thanks for looking into it @koenbeuk . Is there anything we can help with?

**Comment by anthony-keller** [comment]
Thanks @koenbeuk - we'll test it out today and let you know. Appreciate the quick response.

**Comment by anthony-keller** [comment]
We've had no issues on the new version
