### ISSUE TITLE
Many-to-Many Trigger

### ISSUE THREAD

**Issue by TheWillard** [koenbeuk/EntityFrameworkCore.Triggered#158]
Hello,

thanks for the library. I'm wondering if it's possible to get a trigger working for a many-to-many relationship which is configured with:

```
modelBuilder.Entity<Author>()
    .HasMany(x => x.Books)
    .WithMany(x => x.Authors);
```

I pushed a [small example](https://github.com/TheWillard/triggered-many-to-many) where I tried to get it working, you can see that the Triggers for Author and Book are not called when I [save a change to the collection](https://github.com/TheWillard/triggered-many-to-many/blob/8e7dd2013842aa7f2f558b50afd761b7711feb60/triggered-many-to-many/Controllers/TestController.cs#L34-L36).

**Comment by koenbeuk** [comment]
@TheWillard That is because neither the book nor the author has changed according to EF. Instead, an implicit entity is created of type `Dictionary<string, object>`.

You can actually trigger on this by implementing a Trigger that catches those:
`public class ManyToManyTrigger : IBeforeSaveTrigger<Dictionary<string, object>> { ... }`

This of course will trigger for all implicit many-to-many types which is probably not what you want. Instead, I recommend explicit many to many entity types for those relationships that need triggers. Open to proposals though

**Comment by TheWillard** [comment]
I will use an explicit relationship then. Thanks for the fast response :)
